// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#include "ui.h"
#include "ble_client.h"

void on_scan_start_clicked(lv_event_t * e)
{
	ble_scan_and_populate();
}

void on_connect_clicked(lv_event_t * e)
{
	ble_connect_selected();
}

void on_rescan_clicked(lv_event_t * e)
{
	ble_scan_and_populate();
}

void on_apply_sleep_clicked(lv_event_t * e)
{
	ble_apply_sleep();
}

void on_tare_clicked(lv_event_t * e)
{
	ble_tare();
}

void on_disconnect_clicked(lv_event_t * e)
{
	ble_disconnect();
}
