// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_scan_start_clicked(lv_event_t * e);
void on_connect_clicked(lv_event_t * e);
void on_rescan_clicked(lv_event_t * e);
void on_apply_sleep_clicked(lv_event_t * e);
void on_tare_clicked(lv_event_t * e);
void on_disconnect_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
