// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#define DIGIT_COUNT 5

extern int digits[];
extern bool is_negative;
extern lv_obj_t *digit_labels[];
extern lv_obj_t *sign_label;

void update_display();
void digit_increment(lv_event_t * e);
void digit_decrement(lv_event_t * e);
void toggle_sign(lv_event_t * e);
void getFormattedValue(char *buffer, size_t size);
void on_Button8_value_changed_1(lv_event_t * e);

void disconnect(lv_event_t * e);
void connect_handler(lv_event_t * e);
void scan_handler(lv_event_t * e);
void on_Button8_value_changed_1(lv_event_t * e);
void keyboard_event_handler_1(lv_event_t * e);
void on_switch_value_changed(lv_event_t * e);
void Button_event_handler_1(lv_event_t * e);
void Button_event_handler_2(lv_event_t * e);
void ZEROSer_event(lv_event_t * e);
void VRef_event(lv_event_t * e);
void measure_event(lv_event_t * e);
void daytime_event(lv_event_t * e);
//void meaure_start_stop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
