; Monita Flex v3.03 BLE 子機
; HX711×4ch + DS3231 + DS18B20 + BLE アドバタイズ + RTC2 ディープスリープ

[env:seeed_xiao_nrf52840_sense]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200
lib_deps =
  paulstoffregen/OneWire
  milesburton/DallasTemperature
