[env:seeed-xiao-afruitnrf52-nrf52840-sense]

platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino

monitor_speed = 115200

lib_extra_dirs =
    /Users/takasaki/Documents/Arduino/libraries