; 検証 Step3: TCA9534単体（4052 MUX A/B切り替え）
; XIAO nRF52840 (non-Sense)

[env:seeed_xiao_nrf52840]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_TINYUSB
