; 検証 Step8: DS18B20 1-Wire 温度センサ読み取り
; XIAO nRF52840 (non-Sense)

[env:seeed_xiao_nrf52840]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
lib_deps =
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.9.0
build_flags =
  -D USE_TINYUSB
