; 検証 Step14: SD カード書き込みテスト
; XIAO nRF52840 (Sense)

[env:seeed_xiao_nrf52840_sense]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_TINYUSB
lib_deps =
  arduino-libraries/SD@^1.2.4
