; 検証 Step17: Sigfox モジュール（BRKLSM100）の Device ID / PAC 取得
; XIAO nRF52840 Sense + Monita Flex v3.03 基板

[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200
; upload_port = /dev/cu.usbmodemXXXX
