[env:seeed-xiao-afruitnrf52-nrf52840-sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino

monitor_speed = 115200
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
build_flags =
    -DUSE_TINYUSB
lib_ldf_mode = deep

lib_deps =
    /Users/takasaki/.platformio/packages/framework-arduinoadafruitnrf52/libraries/Adafruit_TinyUSB_Arduino
    /Users/takasaki/.platformio/packages/framework-arduinoadafruitnrf52/libraries/SPI
    seeed-studio/Seeed Arduino LSM6DS3@^2.0.5
    https://github.com/stm32duino/LSM6DSO32.git
