; 検証 Step6: TCA9546A チャンネル切り替え + I2Cスキャン
; XIAO nRF52840 (non-Sense)

[env:seeed_xiao_nrf52840]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_TINYUSB
