; 検証 Step7: TCA9546A経由 DS3231 4ch読み取り
; XIAO ESP32C3 (Flex v3.2基板)

[env:seeed_xiao_esp32c3]
platform  = espressif32
board     = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/RTClib@^2.1.4
  adafruit/Adafruit BusIO@^1.16.0
