; 検証 Step4: BLE GATT 接続（親機 = Peripheral）
[env:seeed_xiao_nrf52840]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags = -D USE_TINYUSB
