; 検証 Step1: 電源・LED・3V3_SW
; XIAO nRF52840 (non-Sense)

[env:seeed_xiao_nrf52840]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags =
  -D USE_TINYUSB
