; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-wrover-e-8m]
platform = espressif32
board = upesy_wrover
framework = arduino

board_build.f_cpu      = 240000000L
build_flags =
  -DMODE_LCD=2
  -DCORE_DEBUG_LEVEL=0

; フラッシュ関連
;board_build.flash_mode = dio
;board_build.flash_freq = 40m 
board_build.flash_mode = qio          ; 不安定なら dio に
board_build.f_flash    = 80000000L    ; 不安定なら 40000000L
board_build.flash_size  = 16MB
board_upload.flash_size = 16MB

; パーティション（下のCSVファイル名）
board_build.partitions = partitions_ffat.csv

; PSRAM あり（WROVER）
board_build.psram = enabled

upload_speed = 921600
upload_port = /dev/cu.usbserial-D309SBD0
monitor_speed = 115200
