; Monita Flex v3.03 BLE 親機（Gateway 暫定版）
; DS3231 時刻管理 + BLE スキャン + RTC2 ディープスリープ

[env:seeed_xiao_nrf52840_sense]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840-sense
framework = arduino
monitor_speed = 115200
