// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
void debug_print(const char* message);
extern int current_screen;
///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label25;
lv_obj_t *ui_Label_Ver;
lv_obj_t *ui_Spinner1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t *ui_Screen2;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Dropdown1;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Button9;
void ui_event_Button9( lv_event_t * e);
lv_obj_t *ui_Label24;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t *ui_Screen3;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label1;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label4;
void ui_event_Button304( lv_event_t * e);
lv_obj_t *ui_Button304;
lv_obj_t *ui_Label304;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t *ui_Screen4;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Dropdown3;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;
//void ui_event_TextArea4( lv_event_t * e);
//lv_obj_t *ui_TextArea4;
void ui_event_Button8( lv_event_t * e);
lv_obj_t *ui_Button8;
lv_obj_t *ui_Label10;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label11;
//void ui_event_Keyboard1( lv_event_t * e);
//lv_obj_t *ui_Keyboard1;
lv_obj_t *ui_Checkbox402;
lv_obj_t *ui_Label402;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t *ui_Screen5;
lv_obj_t *ui_Label12;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_Label16;
void ui_event_TextArea3( lv_event_t * e);
lv_obj_t *ui_TextArea3;
//extern lv_obj_t * ui_Chart1;
lv_obj_t * ui_Chart1;
lv_obj_t *ui_Label501;
void ui_event_Switch503( lv_event_t * e);
lv_obj_t *ui_Switch503;
lv_obj_t *ui_Label503;

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
lv_obj_t *ui_Screen6;
lv_obj_t *ui_Label600;
void ui_event_Button605( lv_event_t * e);
lv_obj_t *ui_Button605;
lv_obj_t *ui_Label605;
void ui_event_Button601( lv_event_t * e);
lv_obj_t *ui_Button601;
void ui_event_Button602( lv_event_t * e);
lv_obj_t *ui_Button602;
void ui_event_Button603( lv_event_t * e);
lv_obj_t *ui_Button603;
lv_obj_t *ui_Label601;
lv_obj_t *ui_Label602;
lv_obj_t *ui_Label603;
lv_obj_t *ui_TextArea603;
lv_obj_t *ui_Checkbox601;
lv_obj_t *ui_Checkbox602;
void ui_event_Keyboard604( lv_event_t * e);
lv_obj_t *ui_Keyboard604;
void ui_event_Button604( lv_event_t * e);
lv_obj_t *ui_Button604;
void ui_event_TextArea604( lv_event_t * e);
lv_obj_t *ui_TextArea604;
lv_obj_t *ui_Label604;
lv_obj_t *ui_Label6031;

lv_obj_t *ui____initial_actions0;

// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
lv_obj_t *ui_Screen7;
lv_obj_t *ui_Spinner2;
lv_obj_t *ui_Label26;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen4_screen_init);
      current_screen = 3;
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    //char command[5]="SR2";
	//handleUartCommunicationWrapper(command);
    //delay(500);
    is_measuring = true ;
	_ui_screen_change( &ui_Screen5, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen5_screen_init);
    current_screen = 4;
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen6, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen6_screen_init);
      current_screen = 5;
}
}
void ui_event_Button304( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      disconnect( e );
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      connect_handler( e );
}
}
void ui_event_Button9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      scan_handler( e );
}
}
/*
void ui_event_TextArea4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea4);
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
*/

void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    if(GATT_command_receive){
    nav_to_menu_after_cmd = true;
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen7_screen_init);
      current_screen = 6;
    }
    else{
        _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen3_screen_init);
        setCheckboxChecked(ui_Checkbox402, false);
        current_screen = 2;
    }
     //lv_textarea_set_text(ui_TextArea4, "");
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
    //char command[5]="ME";
	//handleUartCommunicationWrapper(command);
    is_measuring = false ;
    if(GATT_command_receive){
    nav_to_menu_after_cmd = true;
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen7_screen_init);
        current_screen = 6;
    }
    else{
        _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen3_screen_init);
        current_screen = 2;
        }
      //lv_obj_clear_state(ui_Switch503, LV_STATE_CHECKED);
    }
}

void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      on_Button8_value_changed_1( e );
}
}
void ui_event_Switch503( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      on_switch_value_changed( e );
}
}
void ui_event_Keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      keyboard_event_handler_1( e );
}
}
void ui_event_TextArea3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
    //
}
void ui_event_Button605( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
    if(GATT_command_receive){
    nav_to_menu_after_cmd = true;
      _ui_screen_change( &ui_Screen7, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen7_screen_init);
       current_screen = 6;   
    }
    else{
        _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen3_screen_init);
        current_screen = 2;
    }
      setCheckboxChecked(ui_Checkbox601, false);
      setCheckboxChecked(ui_Checkbox602, false);
}
}
void ui_event_Button601( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      ZEROSer_event( e );
}
}
void ui_event_Button602( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      VRef_event( e );
}
}
void ui_event_Button603( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      measure_event( e );
}
}
void ui_event_Keyboard604( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      //
}
}
void ui_event_Button604( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      daytime_event( e );
}
}
void ui_event_TextArea604( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard604,  ui_TextArea604);
      _ui_flag_modify( ui_Keyboard604, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard604, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui_Screen2_screen_init();
ui_Screen3_screen_init();
ui_Screen4_screen_init();
ui_Screen5_screen_init();
ui_Screen6_screen_init();
ui_Screen7_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
