// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "NimBLEWrapper.h"
#include "ui.h"
#include <stdio.h>


#include "ui_events.h"
//#define DIGIT_COUNT 5

int digits[DIGIT_COUNT] = {0, 0, 0, 0, 0}; // Default 00000
bool is_negative = false;
lv_obj_t *digit_labels[DIGIT_COUNT];
lv_obj_t *sign_label;

void update_display() {
    static char buffer[8];

    setCheckboxChecked(ui_Checkbox402, false);
    
    // 符号ラベルの更新
    lv_label_set_text(sign_label, is_negative ? "-" : "+");

    // 各桁のラベルを更新
    for (int i = 0; i < DIGIT_COUNT; i++) {
        snprintf(buffer, sizeof(buffer), "%d", digits[i]);
        lv_label_set_text(digit_labels[i], buffer);
    }
}

void digit_increment(lv_event_t * e) {
    int index = (int)lv_event_get_user_data(e);
    if (index == 0) {
        digits[0] = (digits[0] == 0) ? 1 : 0; // Only 0 or 1
    } else {
        digits[index] = (digits[index] + 1) % 10;
    }
    update_display();
}

void digit_decrement(lv_event_t * e) {
    int index = (int)lv_event_get_user_data(e);
    if (index == 0) {
        digits[0] = (digits[0] == 1) ? 0 : 1; // Only 0 or 1
    } else {
        digits[index] = (digits[index] == 0) ? 9 : digits[index] - 1;
    }
    update_display();
}

void toggle_sign(lv_event_t * e) {
    is_negative = !is_negative;
    update_display();
}

// 6桁の値を文字列として取得
void getFormattedValue(char *buffer, size_t size) {
    if (size < 7) return;  // バッファが小さすぎる場合は処理しない（符号 + 5桁 + 終端文字）

    // 符号の決定
    char sign = is_negative ? '-' : '0';  // 負の値なら '-', 正の値なら '0'

    // 5桁の数字を取得
    snprintf(buffer, size, "%c%d%d%d%d%d",
        sign,  // 符号 or 0
        lv_label_get_text(digit_labels[0])[0] - '0',
        lv_label_get_text(digit_labels[1])[0] - '0',
        lv_label_get_text(digit_labels[2])[0] - '0',
        lv_label_get_text(digit_labels[3])[0] - '0',
        lv_label_get_text(digit_labels[4])[0] - '0'
    );
}

// Button8 のイベントで値を送信
void on_Button8_value_changed_1(lv_event_t * e) {

    char formattedValue[7];
    getFormattedValue(formattedValue, sizeof(formattedValue));

    char command[12];  // "DVV" + 6桁 + 終端文字
    snprintf(command, sizeof(command), "DVV%s", formattedValue);
    handleUartCommunicationWrapper("SR0");
    delay(2000);
    handleUartCommunicationWrapper(command);

    debug_print("value:");
    debug_print(formattedValue);
}

void on_switch_value_changed(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    bool state = lv_obj_has_state(obj, LV_STATE_CHECKED);
    
    // Switchの状態に応じた処理をここに追加
    if (state) {
        measurment_mode = true ;
        debug_print("Switch is Fast");
    } else {
        debug_print("Switch is Slow");
        measurment_mode = false ;
    }
}


void Button_event_handler_1(lv_event_t * e) {
    // Dropdownの選択値を取得
    char buf[32];
    lv_dropdown_get_selected_str(ui_Dropdown1, buf, sizeof(buf));
    
    // シリアルに出力
    debug_print(buf);
}

void connect_handler(lv_event_t * e)
{
    char buf[32];
    lv_dropdown_get_selected_str(ui_Dropdown1, buf, sizeof(buf));
   	
   	// アドレスに基づいてmyDeviceを設定する
    setMyDeviceByAddress(buf);
    debug_print("BLE Connect:");
	debug_print(buf);
	
}
void scan_handler(lv_event_t * e)
{
    rescan();
    debug_print("Re-Sacn...");
	
}
void ZEROSer_event(lv_event_t * e)
{
	char command[5]="MX2G";
	handleUartCommunicationWrapper(command);
}

void VRef_event(lv_event_t * e)
{
	char command[5]="MX21";
	handleUartCommunicationWrapper(command);
}
void measure_event(lv_event_t * e)
{
	char command[6]="MX2ES";
	handleUartCommunicationWrapper(command);
}

void daytime_event(lv_event_t * e)
{
	char normalizedRTC[13];
    const char * rtcValue = lv_textarea_get_text(ui_TextArea604);
    //const char * rtcValue ="240829123000";
    if(wrapperNormalizeRTCValue(rtcValue, normalizedRTC)){
    
    char command[15];  // "ST" + 12桁 + 終端文字 = 15バイト必要
    snprintf(command, sizeof(command), "ST%s", normalizedRTC);
    handleUartCommunicationWrapper(command);
    //strcpy(command, "GT");
    //handleUartCommunicationWrapper(command);    
    
	}else{
     lv_textarea_set_text(ui_TextArea604,"Error");
	}
}

void disconnect(lv_event_t * e)
{
	char command[11]="disconnect";
	handleUartCommunicationWrapper(command);
}

/*
void meaure_start_stop(lv_event_t * e)
{
	static bool is_measuring = false;
	debug_print("meaure_start_stop");
	
	if (is_measuring) {
	    char command[6]="ME";
	    handleUartCommunicationWrapper(command);
        is_measuring = false;
        lv_label_set_text(lv_event_get_target(e), "Start Measuring"); // Update label to indicate stopped state
    } else {
        // Start measuring
        is_measuring = true;
        lv_label_set_text(lv_event_get_target(e), "Stop Measuring"); // Update label to indicate running state
    }
}
}
*/
