// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

extern lv_chart_series_t* ui_Chart1_series_1;
//extern lv_coord_t ui_Chart1_series_1_array[];
extern const int CHART_POINTS = 10;

void ui_Screen5_screen_init(void)
{
ui_Screen5 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -100 );
lv_obj_set_y( ui_Label12, -100 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"電圧測定");
lv_obj_set_style_text_font(ui_Label12, &avl_jp_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button6 = lv_btn_create(ui_Screen5);
lv_obj_set_width( ui_Button6, 100);
lv_obj_set_height( ui_Button6, 30);
lv_obj_set_x( ui_Button6, 65 );
lv_obj_set_y( ui_Button6, 90 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 65 );
lv_obj_set_y( ui_Label16, 90 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"戻る");

ui_TextArea3 = lv_textarea_create(ui_Screen5);
lv_obj_set_width( ui_TextArea3, 150);
lv_obj_set_height( ui_TextArea3, 35);
lv_obj_set_x( ui_TextArea3, 45 );
lv_obj_set_y( ui_TextArea3, -95 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea3,"準備完了");
lv_textarea_set_max_length(ui_TextArea3, 8);
lv_textarea_set_one_line(ui_TextArea3, true);

ui_Chart1 = lv_chart_create(ui_Screen5);
lv_obj_set_width( ui_Chart1, 260);
lv_obj_set_height( ui_Chart1, 140);
lv_obj_set_x( ui_Chart1, 25 );
lv_obj_set_y( ui_Chart1, -2 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, -9999, 9999);
lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 0, 0, 0, false, 0);
lv_obj_set_style_text_opa(ui_Chart1, LV_OPA_TRANSP, LV_PART_TICKS | LV_CHART_AXIS_PRIMARY_X);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 5, 2, 5, 2, true, 70);
ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);

ui_Label501 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label501, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label501, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label501, 135 );
lv_obj_set_y( ui_Label501, -90 );
lv_obj_set_align( ui_Label501, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label501,"mV");

ui_Label503 = lv_label_create(ui_Screen5);
lv_obj_set_width( ui_Label503, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label503, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label503, -49 );
lv_obj_set_y( ui_Label503, 107 );
lv_obj_set_align( ui_Label503, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label503,"SLOW / FAST");
lv_obj_set_style_text_font(ui_Label503, &avl_jp_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch503 = lv_switch_create(ui_Screen5);
lv_obj_set_width( ui_Switch503, 50);
lv_obj_set_height( ui_Switch503, 25);
lv_obj_set_x( ui_Switch503, -49 );
lv_obj_set_y( ui_Switch503, 86 );
lv_obj_set_align( ui_Switch503, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Switch503, LV_STATE_CHECKED);


// 初期データを設定
/*
for (int i = 0; i < CHART_POINTS; i++) {
   ui_Chart1_series_1_array[i] = -111;
}
lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
*/

//lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
//lv_chart_series_t* ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
//static lv_coord_t ui_Chart1_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
//lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch503, ui_event_Switch503, LV_EVENT_ALL, NULL);
}
