// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "custom_keyboard.h"

void ui_Screen6_screen_init(void)
{
ui_Screen6 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label600 = lv_label_create(ui_Screen6);
lv_obj_set_width( ui_Label600, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label600, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label600, -100 );
lv_obj_set_y( ui_Label600, -100 );
lv_obj_set_align( ui_Label600, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label600,"設定");
lv_obj_set_style_text_font(ui_Label600, &avl_jp_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button605 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button605, 200);
lv_obj_set_height( ui_Button605, 30);
lv_obj_set_x( ui_Button605, 0 );
lv_obj_set_y( ui_Button605, 90 );
lv_obj_set_align( ui_Button605, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button605, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button605, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button605, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button605, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label605 = lv_label_create(ui_Screen6);
lv_obj_set_width( ui_Label605, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label605, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label605, 0 );
lv_obj_set_y( ui_Label605, 90 );
lv_obj_set_align( ui_Label605, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label605,"戻る");

ui_Button601 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button601, 100);
lv_obj_set_height( ui_Button601, 20);
lv_obj_set_x( ui_Button601, -80 );
lv_obj_set_y( ui_Button601, -70 );
lv_obj_set_align( ui_Button601, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button601, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button601, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button601, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button601, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button602 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button602, 100);
lv_obj_set_height( ui_Button602, 20);
lv_obj_set_x( ui_Button602, -79 );
lv_obj_set_y( ui_Button602, -40 );
lv_obj_set_align( ui_Button602, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button602, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button602, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button602, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button602, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button603 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button603, 100);
lv_obj_set_height( ui_Button603, 30);
lv_obj_set_x( ui_Button603, -80 );
lv_obj_set_y( ui_Button603, 0 );
lv_obj_set_align( ui_Button603, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button603, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button603, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button603, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button603, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6031 = lv_label_create(ui_Screen6);
lv_obj_set_width( ui_Label6031, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6031, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6031, 137 );
lv_obj_set_y( ui_Label6031, 0 );
lv_obj_set_align( ui_Label6031, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6031,"mV");

ui_Label601 = lv_label_create(ui_Screen6);
lv_obj_set_width( ui_Label601, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label601, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label601, -80 );
lv_obj_set_y( ui_Label601, -70 );
lv_obj_set_align( ui_Label601, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label601,"セロセット");

ui_Label602 = lv_label_create(ui_Screen6);
lv_obj_set_width( ui_Label602, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label602, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label602, -80 );
lv_obj_set_y( ui_Label602, -40 );
lv_obj_set_align( ui_Label602, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label602,"スパンセット");

ui_Label603 = lv_label_create(ui_Screen6);
lv_obj_set_width( ui_Label603, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label603, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label603, -80 );
lv_obj_set_y( ui_Label603, 0 );
lv_obj_set_align( ui_Label603, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label603,"スポット測定");

ui_TextArea603 = lv_textarea_create(ui_Screen6);
lv_obj_set_width( ui_TextArea603, 133);
lv_obj_set_height( ui_TextArea603, 30);
lv_obj_set_x( ui_TextArea603, 56 );
lv_obj_set_y( ui_TextArea603, 0 );
lv_obj_set_align( ui_TextArea603, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea603,"準備完了");
lv_textarea_set_one_line(ui_TextArea603, true);


ui_Checkbox601 = lv_checkbox_create(ui_Screen6);
lv_checkbox_set_text(ui_Checkbox601,"Done");
lv_obj_set_width( ui_Checkbox601, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox601, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox601, 60 );
lv_obj_set_y( ui_Checkbox601, -70 );
lv_obj_set_align( ui_Checkbox601, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox601, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag(ui_Checkbox601, LV_OBJ_FLAG_CLICKABLE);
lv_obj_set_style_bg_opa(ui_Checkbox601, LV_OPA_TRANSP, LV_PART_INDICATOR | LV_STATE_DEFAULT); // 四角形を透明に
lv_obj_set_style_border_width(ui_Checkbox601, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);      // ボーダーを非表示


ui_Checkbox602 = lv_checkbox_create(ui_Screen6);
lv_checkbox_set_text(ui_Checkbox602,"Done");
lv_obj_set_width( ui_Checkbox602, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox602, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox602, 60 );
lv_obj_set_y( ui_Checkbox602, -40 );
lv_obj_set_align( ui_Checkbox602, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox602, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag(ui_Checkbox602, LV_OBJ_FLAG_CLICKABLE);
lv_obj_set_style_bg_opa(ui_Checkbox602, LV_OPA_TRANSP, LV_PART_INDICATOR | LV_STATE_DEFAULT); // 四角形を透明に
lv_obj_set_style_border_width(ui_Checkbox602, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);      // ボーダーを非表示


ui_Button604 = lv_btn_create(ui_Screen6);
lv_obj_set_width( ui_Button604, 100);
lv_obj_set_height( ui_Button604, 30);
lv_obj_set_x( ui_Button604, -80 );
lv_obj_set_y( ui_Button604, 45 );
lv_obj_set_align( ui_Button604, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button604, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button604, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button604, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button604, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea604 = lv_textarea_create(ui_Screen6);
lv_obj_set_width( ui_TextArea604, 150);
lv_obj_set_height( ui_TextArea604, 30);
lv_obj_set_x( ui_TextArea604, 65 );
lv_obj_set_y( ui_TextArea604, 45 );
lv_obj_set_align( ui_TextArea604, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea604,"YYMMDDhhmmss");
lv_textarea_set_max_length(ui_TextArea604, 19);
lv_textarea_set_one_line(ui_TextArea604, true);

ui_Label604 = lv_label_create(ui_Screen6);
lv_obj_set_width( ui_Label604, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label604, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label604, -80 );
lv_obj_set_y( ui_Label604, 45 );
lv_obj_set_align( ui_Label604, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label604,"日時設定");

ui_Keyboard604 = create_custom_keyboard(ui_Screen6);
//lv_keyboard_set_mode(ui_Keyboard604,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard604, 109);
lv_obj_set_height( ui_Keyboard604, 120);
lv_obj_set_x( ui_Keyboard604, -90 );
lv_obj_set_y( ui_Keyboard604, -10 );
lv_obj_set_align( ui_Keyboard604, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard604, LV_OBJ_FLAG_HIDDEN ); 

lv_obj_add_event_cb(ui_Button605, ui_event_Button605, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button601, ui_event_Button601, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button602, ui_event_Button602, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button603, ui_event_Button603, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button604, ui_event_Button604, LV_EVENT_ALL, NULL);

lv_obj_add_event_cb(ui_TextArea604, ui_event_TextArea604, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard604, ui_event_Keyboard604, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard604,ui_TextArea604);
}
