// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H
void debug_print(const char* message);

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label25;
extern lv_obj_t *ui_Label_Ver;
extern lv_obj_t *ui_Spinner1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Dropdown1;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label6;
void ui_event_Button9( lv_event_t * e);
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label24;
//extern lv_obj_t* screens[7];
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label4;
void ui_event_Button304( lv_event_t * e);
extern lv_obj_t *ui_Button304;
extern lv_obj_t *ui_Label304;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Dropdown3;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
//void ui_event_TextArea4( lv_event_t * e);
//extern lv_obj_t *ui_TextArea4;
void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label10;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label11;
//void ui_event_Keyboard1( lv_event_t * e);
//extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_Checkbox402;
extern lv_obj_t *ui_Label402;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t *ui_Screen5;
extern lv_obj_t *ui_Label12;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label16;
void ui_event_TextArea3( lv_event_t * e);
extern lv_obj_t *ui_TextArea3;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_Label501;
void ui_event_Switch503( lv_event_t * e);
extern lv_obj_t *ui_Switch503;
extern lv_obj_t *ui_Label503;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t *ui_Screen6;
extern lv_obj_t *ui_Label600;
void ui_event_Button605( lv_event_t * e);
extern lv_obj_t *ui_Button605;
extern lv_obj_t *ui_Label605;
void ui_event_Button601( lv_event_t * e);
extern lv_obj_t *ui_Button601;
void ui_event_Button602( lv_event_t * e);
extern lv_obj_t *ui_Button602;
void ui_event_Button603( lv_event_t * e);
extern lv_obj_t *ui_Button603;
extern lv_obj_t *ui_Label601;
extern lv_obj_t *ui_Label602;
extern lv_obj_t *ui_Label603;
extern lv_obj_t *ui_TextArea603;
extern lv_obj_t *ui_Checkbox601;
extern lv_obj_t *ui_Checkbox602;
void ui_event_Keyboard604( lv_event_t * e);
extern lv_obj_t *ui_Keyboard604;
void ui_event_TextArea604( lv_event_t * e);
extern lv_obj_t *ui_TextArea604;
void ui_event_Button604( lv_event_t * e);
extern lv_obj_t *ui_Button604;
extern lv_obj_t *ui_Label604;
extern lv_obj_t *ui_Label6031;
extern lv_obj_t *ui____initial_actions0;
//screen: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t *ui_Screen7;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui_Label26;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_332829496);   // assets/logo (3) (1).png

void ui_init(void);
void setCheckboxChecked(lv_obj_t *checkbox, bool checked);
extern bool is_measuring;          // 計測中
extern bool measurment_mode;       // Fast/Slow
extern bool nav_to_menu_after_cmd; // コマンド完了後メニューへ
extern bool GATT_command_receive;  // BLEビジー

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
