// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_events.h"  // ← `ui_events.c` の関数を使えるようにする

extern int digits[];
extern bool is_negative;
extern lv_obj_t *digit_labels[];
extern lv_obj_t *sign_label;
extern void update_display();
extern void digit_increment(lv_event_t * e);
extern void digit_decrement(lv_event_t * e);
extern void toggle_sign(lv_event_t * e);

//#include "custom_keyboard.h"

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

    // ボタンのスタイルを設定
    static lv_style_t btn_style;
    lv_style_init(&btn_style);
    lv_style_set_bg_color(&btn_style, lv_color_hex(0xAFAFAF)); // 他のボタンと同じ色に変更
    //　lv_style_set_border_width(&btn_style, 2);
    lv_style_set_radius(&btn_style, 8);
    lv_style_set_text_color(&btn_style, lv_color_hex(0xFFFFFF)); // 白文字

    // 符号（+ / -）ボタン
    lv_obj_t *sign_btn = lv_btn_create(ui_Screen4);
    lv_obj_set_size(sign_btn, 30, 20);
    lv_obj_align(sign_btn, LV_ALIGN_TOP_MID, -80, 75);
    lv_obj_add_event_cb(sign_btn, toggle_sign, LV_EVENT_CLICKED, NULL);
    lv_obj_add_style(sign_btn, &btn_style, LV_PART_MAIN);

    sign_label = lv_label_create(sign_btn);
    lv_obj_set_style_text_font(sign_label , &avl_jp_18, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_label_set_text(sign_label, "+");
    lv_obj_align(sign_label, LV_ALIGN_CENTER, 0, 0);

    // Create digit controls
    for (int i = 0; i < DIGIT_COUNT; i++) {
        // Up button
        lv_obj_t * up_btn = lv_btn_create(ui_Screen4);
        lv_obj_set_size(up_btn, 20, 20);
        lv_obj_align(up_btn, LV_ALIGN_TOP_MID, -50 + (i * 25), 50);
        lv_obj_add_event_cb(up_btn, digit_increment, LV_EVENT_CLICKED, (void*)i);
        lv_obj_add_style(up_btn, &btn_style, LV_PART_MAIN);

        lv_label_t * up_label = lv_label_create(up_btn);
        lv_obj_set_style_text_font(up_label , &avl_jp_18, LV_PART_MAIN| LV_STATE_DEFAULT);
        lv_label_set_text(up_label, "+");
        lv_obj_align(up_label, LV_ALIGN_CENTER, 0, 0);

        // Digit label
        digit_labels[i] = lv_label_create(ui_Screen4);
        lv_obj_align(digit_labels[i], LV_ALIGN_TOP_MID, -50 + (i * 25), 75);
        lv_label_set_text_fmt(digit_labels[i], "%d", digits[i]);

        // Down button
        lv_obj_t * down_btn = lv_btn_create(ui_Screen4);
        lv_obj_set_size(down_btn, 20, 20);
        lv_obj_align(down_btn, LV_ALIGN_TOP_MID, -50 + (i * 25), 95);
        lv_obj_add_event_cb(down_btn, digit_decrement, LV_EVENT_CLICKED, (void*)i);
        lv_obj_add_style(down_btn, &btn_style, LV_PART_MAIN);

        lv_label_t * down_label = lv_label_create(down_btn);
        lv_obj_set_style_text_font(down_label , &avl_jp_18, LV_PART_MAIN| LV_STATE_DEFAULT);
        lv_label_set_text(down_label, "-");
        lv_obj_align(down_label, LV_ALIGN_CENTER, 0, 0);
    }

ui_Label7 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -100 );
lv_obj_set_y( ui_Label7, -100 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"電圧出力");
lv_obj_set_style_text_font(ui_Label7, &avl_jp_18, LV_PART_MAIN| LV_STATE_DEFAULT);

/*
ui_Label9 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -90 );
lv_obj_set_y( ui_Label9, -30 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Output");

ui_TextArea4 = lv_textarea_create(ui_Screen4);
lv_obj_set_width( ui_TextArea4, 130);
lv_obj_set_height( ui_TextArea4, 30);
lv_obj_set_x( ui_TextArea4, 35 );
lv_obj_set_y( ui_TextArea4, -55 );
lv_obj_set_align( ui_TextArea4, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea4,"Ready");
lv_textarea_set_max_length(ui_TextArea4, 7);
lv_textarea_set_one_line(ui_TextArea4, true);
*/

ui_Button8 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button8, 100);
lv_obj_set_height( ui_Button8, 30);
lv_obj_set_x( ui_Button8, -50 );
lv_obj_set_y( ui_Button8, 40 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -50 );
lv_obj_set_y( ui_Label10, 40 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"出力開始");

ui_Button5 = lv_btn_create(ui_Screen4);
lv_obj_set_width( ui_Button5, 200);
lv_obj_set_height( ui_Button5, 30);
lv_obj_set_x( ui_Button5, 0 );
lv_obj_set_y( ui_Button5, 90 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xAFAFAF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 0 );
lv_obj_set_y( ui_Label11, 90 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"戻る");

/*
//ui_Keyboard1 = lv_keyboard_create(ui_Screen4);
ui_Keyboard1 = create_custom_keyboard(ui_Screen4);
//lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 109);
lv_obj_set_height( ui_Keyboard1, 120);
lv_obj_set_x( ui_Keyboard1, -90 );
lv_obj_set_y( ui_Keyboard1, -10 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN );   /// Flags
*/

ui_Checkbox402 = lv_checkbox_create(ui_Screen4);
lv_checkbox_set_text(ui_Checkbox402,"Done");
lv_obj_set_width( ui_Checkbox402, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Checkbox402, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Checkbox402, 60 );
lv_obj_set_y( ui_Checkbox402, 40 );
lv_obj_set_align( ui_Checkbox402, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Checkbox402, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag(ui_Checkbox402, LV_OBJ_FLAG_CLICKABLE);
lv_obj_set_style_bg_opa(ui_Checkbox402, LV_OPA_TRANSP, LV_PART_INDICATOR | LV_STATE_DEFAULT); // 四角形を透明に
lv_obj_set_style_border_width(ui_Checkbox402, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);      // ボーダーを非表示

ui_Label402 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label402, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label402, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label402, 85 );
lv_obj_set_y( ui_Label402, -35 );
lv_obj_set_align( ui_Label402, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label402,"mV");

//lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
//lv_keyboard_set_textarea(ui_Keyboard1,ui_TextArea4);
//lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
}

