// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
extern const char* VERSION;
extern const char* BUILD_DATETIME; 

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_332829496);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 101
lv_obj_set_x( ui_Image4, 0 );
lv_obj_set_y( ui_Image4, -20 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, 50 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"AccuVoltLink");
lv_obj_set_style_text_font(ui_Label3, &avl_jp_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, 0 );
lv_obj_set_y( ui_Label25, 85 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"デバイススキャン中");
lv_obj_set_style_text_font(ui_Label25, &avl_jp_10, LV_PART_MAIN| LV_STATE_DEFAULT);

char versionText[64];
snprintf(versionText, sizeof(versionText),"Version %s (%s)", VERSION, BUILD_DATETIME);
ui_Label_Ver = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_Ver, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Ver, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Ver, 0 );
lv_obj_set_y( ui_Label_Ver, 105 );
lv_obj_set_align( ui_Label_Ver, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Ver,versionText);
lv_obj_set_style_text_font(ui_Label_Ver, &avl_jp_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner1, 17);
lv_obj_set_height( ui_Spinner1, 34);
lv_obj_set_x( ui_Spinner1, -60 );
lv_obj_set_y( ui_Spinner1, 92 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_width(ui_Spinner1, 3, LV_PART_INDICATOR| LV_STATE_DEFAULT);

}
