// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#include "../ui.h"

lv_obj_t *ui_DviceList = NULL;lv_obj_t *ui_Dropdown1 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Label2 = NULL;
// event funtions
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_connect_clicked( e );
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_rescan_clicked( e );
}
}

// build funtions

void ui_DviceList_screen_init(void)
{
ui_DviceList = lv_obj_create(NULL);
lv_obj_clear_flag( ui_DviceList, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dropdown1 = lv_dropdown_create(ui_DviceList);
lv_obj_set_width( ui_Dropdown1, 249);
lv_obj_set_height( ui_Dropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown1, 0 );
lv_obj_set_y( ui_Dropdown1, -33 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
// ★2026-09-12: LV_FONT_DEFAULTはlv_conf.hでavl_jp_14（日本語サブセットフォント）に
// 差し替え済みだが、このフォントにはLVGL標準の開閉矢印シンボル(LV_SYMBOL_DOWN)の
// グリフが含まれていない。一度は組み込みフォント(lv_font_montserrat_14)へ差し替えて
// 試したが、そちらは逆に日本語グリフを一切持たないため、プレースホルダー
// 「デバイスが見つかりません」等が全て文字化けする回帰を起こした（実機で確認）。
// ドロップダウンの矢印記号とテキストは同じフォント・同じ描画で扱われ分離できないため、
// フォントの差し替えではなく、矢印記号自体をこのフォントに含まれるASCII文字に置き換える。
lv_dropdown_set_symbol(ui_Dropdown1, "v");

ui_Button2 = lv_btn_create(ui_DviceList);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 29);
lv_obj_set_x( ui_Button2, -74 );
lv_obj_set_y( ui_Button2, 25 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"接続");

ui_Button3 = lv_btn_create(ui_DviceList);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 29);
lv_obj_set_x( ui_Button3, 60 );
lv_obj_set_y( ui_Button3, 25 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x454444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"再スキャン");

lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_DviceList_screen_destroy(void)
{
   if (ui_DviceList) lv_obj_del(ui_DviceList);

// NULL screen variables
ui_DviceList= NULL;
ui_Dropdown1= NULL;
ui_Button2= NULL;
ui_Label3= NULL;
ui_Button3= NULL;
ui_Label2= NULL;

}
