// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#ifndef UI_DVICELIST_H
#define UI_DVICELIST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DviceList
extern void ui_DviceList_screen_init(void);
extern void ui_DviceList_screen_destroy(void);
extern lv_obj_t *ui_DviceList;
extern lv_obj_t *ui_Dropdown1;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label3;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

