// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#include "../ui.h"

lv_obj_t *ui_Measure = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Spinbox1 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Button5 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Button6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Button8 = NULL;lv_obj_t *ui_Label10 = NULL;
// event funtions
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_apply_sleep_clicked( e );
}
}

void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_tare_clicked( e );
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_disconnect_clicked( e );
}
}

void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_Spinbox1, -1);
}
}

void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_Spinbox1, 1);
}
}

// build funtions

void ui_Measure_screen_init(void)
{
ui_Measure = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Measure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Measure);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -105 );
lv_obj_set_y( ui_Label4, -103 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Sleep: -- min");

ui_Spinbox1 = lv_spinbox_create(ui_Measure);
lv_obj_set_width( ui_Spinbox1, 70);
lv_obj_set_height( ui_Spinbox1, 42);
lv_obj_set_x( ui_Spinbox1, -98 );
lv_obj_set_y( ui_Spinbox1, -61 );
lv_obj_set_align( ui_Spinbox1, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_Spinbox1, 2, 2);
lv_spinbox_set_range( ui_Spinbox1, 0,7200 );
lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

ui_Button4 = lv_btn_create(ui_Measure);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 28);
lv_obj_set_x( ui_Button4, 28 );
lv_obj_set_y( ui_Button4, -65 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Apply");

ui_Button5 = lv_btn_create(ui_Measure);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 29);
lv_obj_set_x( ui_Button5, 29 );
lv_obj_set_y( ui_Button5, -28 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Tare");

ui_Button6 = lv_btn_create(ui_Measure);
lv_obj_set_width( ui_Button6, 100);
lv_obj_set_height( ui_Button6, 30);
lv_obj_set_x( ui_Button6, 27 );
lv_obj_set_y( ui_Button6, 11 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_Button6);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Disconnect");

ui_Label8 = lv_label_create(ui_Measure);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, 13 );
lv_obj_set_y( ui_Label8, -41 );
lv_obj_set_align( ui_Label8, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_Label8,"BLE: --\nLast: -- ");

ui_Button7 = lv_btn_create(ui_Measure);
lv_obj_set_width( ui_Button7, 24);
lv_obj_set_height( ui_Button7, 31);
lv_obj_set_x( ui_Button7, -146 );
lv_obj_set_y( ui_Button7, -62 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"-");

ui_Button8 = lv_btn_create(ui_Measure);
lv_obj_set_width( ui_Button8, 24);
lv_obj_set_height( ui_Button8, 31);
lv_obj_set_x( ui_Button8, -49 );
lv_obj_set_y( ui_Button8, -62 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_Button8);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"+");

lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);

}

void ui_Measure_screen_destroy(void)
{
   if (ui_Measure) lv_obj_del(ui_Measure);

// NULL screen variables
ui_Measure= NULL;
ui_Label4= NULL;
ui_Spinbox1= NULL;
ui_Button4= NULL;
ui_Label5= NULL;
ui_Button5= NULL;
ui_Label6= NULL;
ui_Button6= NULL;
ui_Label7= NULL;
ui_Label8= NULL;
ui_Button7= NULL;
ui_Label9= NULL;
ui_Button8= NULL;
ui_Label10= NULL;

}
