// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#ifndef UI_MEASURE_H
#define UI_MEASURE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Measure
extern void ui_Measure_screen_init(void);
extern void ui_Measure_screen_destroy(void);
extern lv_obj_t *ui_Measure;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Spinbox1;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label5;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label6;
extern void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
extern void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label9;
extern void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

