// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#ifndef UI_MESURE_H
#define UI_MESURE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Mesure
extern void ui_Mesure_screen_init(void);
extern void ui_Mesure_screen_destroy(void);
extern lv_obj_t *ui_Mesure;
extern lv_obj_t *ui_CH1;
extern lv_obj_t *ui_CH2;
extern lv_obj_t *ui_CH3;
extern lv_obj_t *ui_CH4;
extern lv_obj_t *ui_CH5;
extern lv_obj_t *ui_CH6;
extern lv_obj_t *ui_CH7;
extern lv_obj_t *ui_CH8;
extern void ui_event_start( lv_event_t * e);
extern lv_obj_t *ui_start;
extern lv_obj_t *ui_Label12;
extern void ui_event_stop( lv_event_t * e);
extern lv_obj_t *ui_stop;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_timestamp;
extern void ui_event_discnnect( lv_event_t * e);
extern lv_obj_t *ui_discnnect;
extern lv_obj_t *ui_Label14;
extern void ui_event_discnnect1( lv_event_t * e);
extern lv_obj_t *ui_discnnect1;
extern lv_obj_t *ui_settingBotton;
extern lv_obj_t *ui_Label11;
// CUSTOM VARIABLES
extern lv_obj_t *uic_stop;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

