// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#include "../ui.h"

lv_obj_t *uic_stop;
lv_obj_t *ui_Mesure = NULL;lv_obj_t *ui_CH1 = NULL;lv_obj_t *ui_CH2 = NULL;lv_obj_t *ui_CH3 = NULL;lv_obj_t *ui_CH4 = NULL;lv_obj_t *ui_CH5 = NULL;lv_obj_t *ui_CH6 = NULL;lv_obj_t *ui_CH7 = NULL;lv_obj_t *ui_CH8 = NULL;lv_obj_t *ui_start = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_stop = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_timestamp = NULL;lv_obj_t *ui_discnnect = NULL;lv_obj_t *ui_Label14 = NULL;lv_obj_t *ui_discnnect1 = NULL;lv_obj_t *ui_settingBotton = NULL;lv_obj_t *ui_Label11 = NULL;
// event funtions
void ui_event_start( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_start_clicked( e );
}
}

void ui_event_stop( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_stop_clicked( e );
}
}

void ui_event_discnnect( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_disconnect_clicked( e );
}
}

void ui_event_discnnect1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_settings_clicked( e );
}
}

// build funtions

void ui_Mesure_screen_init(void)
{
ui_Mesure = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Mesure, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CH1 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH1, 33 );
lv_obj_set_y( ui_CH1, 18 );
lv_label_set_text(ui_CH1,"CH1:--uS");

ui_CH2 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH2, 33 );
lv_obj_set_y( ui_CH2, 47 );
lv_label_set_text(ui_CH2,"CH2:--uS");

ui_CH3 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH3, 33 );
lv_obj_set_y( ui_CH3, 80 );
lv_label_set_text(ui_CH3,"CH3:--uS");

ui_CH4 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH4, 33 );
lv_obj_set_y( ui_CH4, 110 );
lv_label_set_text(ui_CH4,"CH4:--mm");

ui_CH5 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH5, 162 );
lv_obj_set_y( ui_CH5, 17 );
lv_label_set_text(ui_CH5,"CH5:--mm");

ui_CH6 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH6, 162 );
lv_obj_set_y( ui_CH6, 47 );
lv_label_set_text(ui_CH6,"CH6:-- temp");

ui_CH7 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH7, 161 );
lv_obj_set_y( ui_CH7, 80 );
lv_label_set_text(ui_CH7,"CH7:--V");

ui_CH8 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_CH8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CH8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CH8, 161 );
lv_obj_set_y( ui_CH8, 111 );
lv_label_set_text(ui_CH8,"CH8:--V");

ui_start = lv_btn_create(ui_Mesure);
lv_obj_set_width( ui_start, 100);
lv_obj_set_height( ui_start, 26);
lv_obj_set_x( ui_start, -91 );
lv_obj_set_y( ui_start, 64 );
lv_obj_set_align( ui_start, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_start, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_start, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_start, lv_color_hex(0x20B53D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_start, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_start);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Start");

ui_stop = lv_btn_create(ui_Mesure);
lv_obj_set_width( ui_stop, 99);
lv_obj_set_height( ui_stop, 29);
lv_obj_set_x( ui_stop, -91 );
lv_obj_set_y( ui_stop, 64 );
lv_obj_set_align( ui_stop, LV_ALIGN_CENTER );
lv_obj_add_state( ui_stop, LV_STATE_USER_2 );     /// States
lv_obj_add_flag( ui_stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_stop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_stop, lv_color_hex(0xF34E4E), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_bg_opa(ui_stop, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_Label13 = lv_label_create(ui_stop);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Stop");

ui_timestamp = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_timestamp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timestamp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timestamp, 34 );
lv_obj_set_y( ui_timestamp, 145 );
lv_label_set_text(ui_timestamp,"timestamp:--");

ui_discnnect = lv_btn_create(ui_Mesure);
lv_obj_set_width( ui_discnnect, 100);
lv_obj_set_height( ui_discnnect, 26);
lv_obj_set_x( ui_discnnect, 97 );
lv_obj_set_y( ui_discnnect, 99 );
lv_obj_set_align( ui_discnnect, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_discnnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_discnnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label14 = lv_label_create(ui_discnnect);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"Disconnect");

ui_discnnect1 = lv_btn_create(ui_Mesure);
lv_obj_set_width( ui_discnnect1, 97);
lv_obj_set_height( ui_discnnect1, 26);
lv_obj_set_x( ui_discnnect1, -93 );
lv_obj_set_y( ui_discnnect1, 100 );
lv_obj_set_align( ui_discnnect1, LV_ALIGN_CENTER );
lv_obj_add_state( ui_discnnect1, LV_STATE_EDITED );     /// States
lv_obj_add_flag( ui_discnnect1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_discnnect1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_grad_color(ui_discnnect1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_discnnect1, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_EDITED );
lv_obj_set_style_bg_opa(ui_discnnect1, 255, LV_PART_MAIN| LV_STATE_EDITED);
lv_obj_set_style_bg_color(ui_discnnect1, lv_color_hex(0x484848), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_bg_opa(ui_discnnect1, 255, LV_PART_MAIN| LV_STATE_USER_1);

ui_settingBotton = lv_label_create(ui_discnnect1);
lv_obj_set_width( ui_settingBotton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingBotton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_settingBotton, LV_ALIGN_CENTER );
lv_label_set_text(ui_settingBotton,"Setting");

ui_Label11 = lv_label_create(ui_Mesure);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 133 );
lv_obj_set_y( ui_Label11, 176 );
lv_label_set_text(ui_Label11,"Status: --");

lv_obj_add_event_cb(ui_start, ui_event_start, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_stop, ui_event_stop, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_discnnect, ui_event_discnnect, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_discnnect1, ui_event_discnnect1, LV_EVENT_ALL, NULL);
uic_stop = ui_stop;

}

void ui_Mesure_screen_destroy(void)
{
   if (ui_Mesure) lv_obj_del(ui_Mesure);

// NULL screen variables
ui_Mesure= NULL;
ui_CH1= NULL;
ui_CH2= NULL;
ui_CH3= NULL;
ui_CH4= NULL;
ui_CH5= NULL;
ui_CH6= NULL;
ui_CH7= NULL;
ui_CH8= NULL;
ui_start= NULL;
ui_Label12= NULL;
uic_stop= NULL;
ui_stop= NULL;
ui_Label13= NULL;
ui_timestamp= NULL;
ui_discnnect= NULL;
ui_Label14= NULL;
ui_discnnect1= NULL;
ui_settingBotton= NULL;
ui_Label11= NULL;

}
