// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#include "../ui.h"

lv_obj_t *ui_SetTime = NULL;lv_obj_t *ui_SetTimeTitle = NULL;lv_obj_t *ui_btnSetTimeBack = NULL;lv_obj_t *ui_btnSetTimeBackLbl = NULL;lv_obj_t *ui_LabelYear = NULL;lv_obj_t *ui_YearMinus = NULL;lv_obj_t *ui_YearMinusLbl = NULL;lv_obj_t *ui_SpinboxYear = NULL;lv_obj_t *ui_YearPlus = NULL;lv_obj_t *ui_YearPlusLbl = NULL;lv_obj_t *ui_LabelMonth = NULL;lv_obj_t *ui_MonthMinus = NULL;lv_obj_t *ui_MonthMinusLbl = NULL;lv_obj_t *ui_SpinboxMonth = NULL;lv_obj_t *ui_MonthPlus = NULL;lv_obj_t *ui_MonthPlusLbl = NULL;lv_obj_t *ui_LabelDay = NULL;lv_obj_t *ui_DayMinus = NULL;lv_obj_t *ui_DayMinusLbl = NULL;lv_obj_t *ui_SpinboxDay = NULL;lv_obj_t *ui_DayPlus = NULL;lv_obj_t *ui_DayPlusLbl = NULL;lv_obj_t *ui_LabelHour = NULL;lv_obj_t *ui_HourMinus = NULL;lv_obj_t *ui_HourMinusLbl = NULL;lv_obj_t *ui_SpinboxHour = NULL;lv_obj_t *ui_HourPlus = NULL;lv_obj_t *ui_HourPlusLbl = NULL;lv_obj_t *ui_LabelMin = NULL;lv_obj_t *ui_MinMinus = NULL;lv_obj_t *ui_MinMinusLbl = NULL;lv_obj_t *ui_SpinboxMin = NULL;lv_obj_t *ui_MinPlus = NULL;lv_obj_t *ui_MinPlusLbl = NULL;lv_obj_t *ui_LabelSec = NULL;lv_obj_t *ui_SecMinus = NULL;lv_obj_t *ui_SecMinusLbl = NULL;lv_obj_t *ui_SpinboxSec = NULL;lv_obj_t *ui_SecPlus = NULL;lv_obj_t *ui_SecPlusLbl = NULL;lv_obj_t *ui_btnSetTimeApply = NULL;lv_obj_t *ui_btnSetTimeApplyLbl = NULL;
// event funtions
void ui_event_btnSetTimeBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_settime_back_clicked( e );
}
}

void ui_event_YearMinus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxYear, -1);
}
}

void ui_event_YearPlus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxYear, 1);
}
}

void ui_event_MonthMinus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxMonth, -1);
}
}

void ui_event_MonthPlus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxMonth, 1);
}
}

void ui_event_DayMinus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxDay, -1);
}
}

void ui_event_DayPlus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxDay, 1);
}
}

void ui_event_HourMinus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxHour, -1);
}
}

void ui_event_HourPlus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxHour, 1);
}
}

void ui_event_MinMinus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxMin, -1);
}
}

void ui_event_MinPlus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxMin, 1);
}
}

void ui_event_SecMinus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxSec, -1);
}
}

void ui_event_SecPlus( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_spinbox_step( ui_SpinboxSec, 1);
}
}

void ui_event_btnSetTimeApply( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      on_settime_apply_clicked( e );
}
}

// build funtions

void ui_SetTime_screen_init(void)
{
ui_SetTime = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SetTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SetTimeTitle = lv_label_create(ui_SetTime);
lv_obj_set_width( ui_SetTimeTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetTimeTitle, LV_SIZE_CONTENT);   /// 1
// ★2026-09-13: 固定x座標だとテキスト幅次第で中心からズレるため、
// 画面上端中央への相対配置(align)に変更して確実に中央に来るようにする。
lv_obj_set_align( ui_SetTimeTitle, LV_ALIGN_TOP_MID );
lv_obj_set_x( ui_SetTimeTitle, 0 );
lv_obj_set_y( ui_SetTimeTitle, 6 );
lv_label_set_text(ui_SetTimeTitle,"時刻設定");

ui_btnSetTimeBack = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_btnSetTimeBack, 50);
lv_obj_set_height( ui_btnSetTimeBack, 22);
lv_obj_set_x( ui_btnSetTimeBack, 6 );
lv_obj_set_y( ui_btnSetTimeBack, 6 );
lv_obj_add_flag( ui_btnSetTimeBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnSetTimeBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnSetTimeBackLbl = lv_label_create(ui_btnSetTimeBack);
lv_obj_set_width( ui_btnSetTimeBackLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_btnSetTimeBackLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_btnSetTimeBackLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_btnSetTimeBackLbl,"戻る");

ui_LabelYear = lv_label_create(ui_SetTime);
lv_obj_set_width( ui_LabelYear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelYear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelYear, 42 );
lv_obj_set_y( ui_LabelYear, 30 );
lv_label_set_text(ui_LabelYear,"Y");

ui_YearMinus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_YearMinus, 16);
lv_obj_set_height( ui_YearMinus, 24);
lv_obj_set_x( ui_YearMinus, 33 );
lv_obj_set_y( ui_YearMinus, 46 );
lv_obj_add_flag( ui_YearMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_YearMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_YearMinusLbl = lv_label_create(ui_YearMinus);
lv_obj_set_width( ui_YearMinusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_YearMinusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_YearMinusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_YearMinusLbl,"-");

ui_SpinboxYear = lv_spinbox_create(ui_SetTime);
lv_obj_set_width( ui_SpinboxYear, 48);
lv_obj_set_height( ui_SpinboxYear, 28);
lv_obj_set_x( ui_SpinboxYear, 51 );
lv_obj_set_y( ui_SpinboxYear, 44 );
lv_spinbox_set_digit_format( ui_SpinboxYear, 4, 4);
lv_spinbox_set_range( ui_SpinboxYear, 2020,2099 );
lv_spinbox_set_cursor_pos(ui_SpinboxYear, 4 - 1);
lv_spinbox_set_value(ui_SpinboxYear, 2026);
// ★2026-09-13: Setting画面のSpinbox1-3と同じく、デフォルトテーマの上下パディングが
// 非対称でテキストが下寄りに見えるため、上下を揃えて垂直中央に近づける。
lv_obj_set_style_pad_top(ui_SpinboxYear, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpinboxYear, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_YearPlus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_YearPlus, 16);
lv_obj_set_height( ui_YearPlus, 24);
lv_obj_set_x( ui_YearPlus, 101 );
lv_obj_set_y( ui_YearPlus, 46 );
lv_obj_add_flag( ui_YearPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_YearPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_YearPlusLbl = lv_label_create(ui_YearPlus);
lv_obj_set_width( ui_YearPlusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_YearPlusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_YearPlusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_YearPlusLbl,"+");

ui_LabelMonth = lv_label_create(ui_SetTime);
lv_obj_set_width( ui_LabelMonth, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMonth, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMonth, 139 );
lv_obj_set_y( ui_LabelMonth, 30 );
lv_label_set_text(ui_LabelMonth,"M");

ui_MonthMinus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_MonthMinus, 15);
lv_obj_set_height( ui_MonthMinus, 24);
lv_obj_set_x( ui_MonthMinus, 131 );
lv_obj_set_y( ui_MonthMinus, 46 );
lv_obj_add_flag( ui_MonthMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MonthMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonthMinusLbl = lv_label_create(ui_MonthMinus);
lv_obj_set_width( ui_MonthMinusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MonthMinusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MonthMinusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_MonthMinusLbl,"-");

ui_SpinboxMonth = lv_spinbox_create(ui_SetTime);
lv_obj_set_width( ui_SpinboxMonth, 34);
lv_obj_set_height( ui_SpinboxMonth, 28);
lv_obj_set_x( ui_SpinboxMonth, 148 );
lv_obj_set_y( ui_SpinboxMonth, 44 );
lv_spinbox_set_digit_format( ui_SpinboxMonth, 2, 2);
lv_spinbox_set_range( ui_SpinboxMonth, 1,12 );
lv_spinbox_set_cursor_pos(ui_SpinboxMonth, 1 - 1);
lv_spinbox_set_value(ui_SpinboxMonth, 1);
lv_obj_set_style_pad_top(ui_SpinboxMonth, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpinboxMonth, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_MonthPlus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_MonthPlus, 15);
lv_obj_set_height( ui_MonthPlus, 24);
lv_obj_set_x( ui_MonthPlus, 184 );
lv_obj_set_y( ui_MonthPlus, 46 );
lv_obj_add_flag( ui_MonthPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MonthPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MonthPlusLbl = lv_label_create(ui_MonthPlus);
lv_obj_set_width( ui_MonthPlusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MonthPlusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MonthPlusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_MonthPlusLbl,"+");

ui_LabelDay = lv_label_create(ui_SetTime);
lv_obj_set_width( ui_LabelDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelDay, 227 );
lv_obj_set_y( ui_LabelDay, 30 );
lv_label_set_text(ui_LabelDay,"D");

ui_DayMinus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_DayMinus, 15);
lv_obj_set_height( ui_DayMinus, 24);
lv_obj_set_x( ui_DayMinus, 219 );
lv_obj_set_y( ui_DayMinus, 46 );
lv_obj_add_flag( ui_DayMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DayMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DayMinusLbl = lv_label_create(ui_DayMinus);
lv_obj_set_width( ui_DayMinusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DayMinusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DayMinusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_DayMinusLbl,"-");

ui_SpinboxDay = lv_spinbox_create(ui_SetTime);
lv_obj_set_width( ui_SpinboxDay, 34);
lv_obj_set_height( ui_SpinboxDay, 28);
lv_obj_set_x( ui_SpinboxDay, 236 );
lv_obj_set_y( ui_SpinboxDay, 44 );
lv_spinbox_set_digit_format( ui_SpinboxDay, 2, 2);
lv_spinbox_set_range( ui_SpinboxDay, 1,31 );
lv_spinbox_set_cursor_pos(ui_SpinboxDay, 1 - 1);
lv_spinbox_set_value(ui_SpinboxDay, 1);
lv_obj_set_style_pad_top(ui_SpinboxDay, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpinboxDay, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_DayPlus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_DayPlus, 15);
lv_obj_set_height( ui_DayPlus, 24);
lv_obj_set_x( ui_DayPlus, 272 );
lv_obj_set_y( ui_DayPlus, 46 );
lv_obj_add_flag( ui_DayPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_DayPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DayPlusLbl = lv_label_create(ui_DayPlus);
lv_obj_set_width( ui_DayPlusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DayPlusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DayPlusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_DayPlusLbl,"+");

ui_LabelHour = lv_label_create(ui_SetTime);
lv_obj_set_width( ui_LabelHour, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHour, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHour, 42 );
lv_obj_set_y( ui_LabelHour, 100 );
lv_label_set_text(ui_LabelHour,"H");

ui_HourMinus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_HourMinus, 16);
lv_obj_set_height( ui_HourMinus, 24);
lv_obj_set_x( ui_HourMinus, 33 );
lv_obj_set_y( ui_HourMinus, 116 );
lv_obj_add_flag( ui_HourMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HourMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HourMinusLbl = lv_label_create(ui_HourMinus);
lv_obj_set_width( ui_HourMinusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HourMinusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HourMinusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_HourMinusLbl,"-");

ui_SpinboxHour = lv_spinbox_create(ui_SetTime);
lv_obj_set_width( ui_SpinboxHour, 34);
lv_obj_set_height( ui_SpinboxHour, 28);
lv_obj_set_x( ui_SpinboxHour, 51 );
lv_obj_set_y( ui_SpinboxHour, 114 );
lv_spinbox_set_digit_format( ui_SpinboxHour, 2, 2);
lv_spinbox_set_range( ui_SpinboxHour, 0,23 );
lv_spinbox_set_cursor_pos(ui_SpinboxHour, 1 - 1);
lv_spinbox_set_value(ui_SpinboxHour, 0);
lv_obj_set_style_pad_top(ui_SpinboxHour, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpinboxHour, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_HourPlus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_HourPlus, 16);
lv_obj_set_height( ui_HourPlus, 24);
lv_obj_set_x( ui_HourPlus, 87 );
lv_obj_set_y( ui_HourPlus, 116 );
lv_obj_add_flag( ui_HourPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_HourPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HourPlusLbl = lv_label_create(ui_HourPlus);
lv_obj_set_width( ui_HourPlusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HourPlusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HourPlusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_HourPlusLbl,"+");

ui_LabelMin = lv_label_create(ui_SetTime);
lv_obj_set_width( ui_LabelMin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMin, 131 );
lv_obj_set_y( ui_LabelMin, 100 );
lv_label_set_text(ui_LabelMin,"Mi");

ui_MinMinus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_MinMinus, 15);
lv_obj_set_height( ui_MinMinus, 24);
lv_obj_set_x( ui_MinMinus, 123 );
lv_obj_set_y( ui_MinMinus, 116 );
lv_obj_add_flag( ui_MinMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MinMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MinMinusLbl = lv_label_create(ui_MinMinus);
lv_obj_set_width( ui_MinMinusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinMinusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MinMinusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinMinusLbl,"-");

ui_SpinboxMin = lv_spinbox_create(ui_SetTime);
lv_obj_set_width( ui_SpinboxMin, 34);
lv_obj_set_height( ui_SpinboxMin, 28);
lv_obj_set_x( ui_SpinboxMin, 140 );
lv_obj_set_y( ui_SpinboxMin, 114 );
lv_spinbox_set_digit_format( ui_SpinboxMin, 2, 2);
lv_spinbox_set_range( ui_SpinboxMin, 0,59 );
lv_spinbox_set_cursor_pos(ui_SpinboxMin, 1 - 1);
lv_spinbox_set_value(ui_SpinboxMin, 0);
lv_obj_set_style_pad_top(ui_SpinboxMin, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpinboxMin, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_MinPlus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_MinPlus, 15);
lv_obj_set_height( ui_MinPlus, 24);
lv_obj_set_x( ui_MinPlus, 176 );
lv_obj_set_y( ui_MinPlus, 116 );
lv_obj_add_flag( ui_MinPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_MinPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MinPlusLbl = lv_label_create(ui_MinPlus);
lv_obj_set_width( ui_MinPlusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinPlusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MinPlusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_MinPlusLbl,"+");

ui_LabelSec = lv_label_create(ui_SetTime);
lv_obj_set_width( ui_LabelSec, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSec, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSec, 219 );
lv_obj_set_y( ui_LabelSec, 100 );
lv_label_set_text(ui_LabelSec,"S");

ui_SecMinus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_SecMinus, 15);
lv_obj_set_height( ui_SecMinus, 24);
lv_obj_set_x( ui_SecMinus, 211 );
lv_obj_set_y( ui_SecMinus, 116 );
lv_obj_add_flag( ui_SecMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SecMinus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SecMinusLbl = lv_label_create(ui_SecMinus);
lv_obj_set_width( ui_SecMinusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SecMinusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SecMinusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_SecMinusLbl,"-");

ui_SpinboxSec = lv_spinbox_create(ui_SetTime);
lv_obj_set_width( ui_SpinboxSec, 34);
lv_obj_set_height( ui_SpinboxSec, 28);
lv_obj_set_x( ui_SpinboxSec, 228 );
lv_obj_set_y( ui_SpinboxSec, 114 );
lv_spinbox_set_digit_format( ui_SpinboxSec, 2, 2);
lv_spinbox_set_range( ui_SpinboxSec, 0,59 );
lv_spinbox_set_cursor_pos(ui_SpinboxSec, 1 - 1);
lv_spinbox_set_value(ui_SpinboxSec, 0);
lv_obj_set_style_pad_top(ui_SpinboxSec, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SpinboxSec, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_SecPlus = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_SecPlus, 15);
lv_obj_set_height( ui_SecPlus, 24);
lv_obj_set_x( ui_SecPlus, 264 );
lv_obj_set_y( ui_SecPlus, 116 );
lv_obj_add_flag( ui_SecPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SecPlus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SecPlusLbl = lv_label_create(ui_SecPlus);
lv_obj_set_width( ui_SecPlusLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SecPlusLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SecPlusLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_SecPlusLbl,"+");

ui_btnSetTimeApply = lv_btn_create(ui_SetTime);
lv_obj_set_width( ui_btnSetTimeApply, 140);
lv_obj_set_height( ui_btnSetTimeApply, 34);
lv_obj_set_x( ui_btnSetTimeApply, 90 );
lv_obj_set_y( ui_btnSetTimeApply, 165 );
lv_obj_add_flag( ui_btnSetTimeApply, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnSetTimeApply, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnSetTimeApplyLbl = lv_label_create(ui_btnSetTimeApply);
lv_obj_set_width( ui_btnSetTimeApplyLbl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_btnSetTimeApplyLbl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_btnSetTimeApplyLbl, LV_ALIGN_CENTER );
lv_label_set_text(ui_btnSetTimeApplyLbl,"設定する");

lv_obj_add_event_cb(ui_btnSetTimeBack, ui_event_btnSetTimeBack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_YearMinus, ui_event_YearMinus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_YearPlus, ui_event_YearPlus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MonthMinus, ui_event_MonthMinus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MonthPlus, ui_event_MonthPlus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DayMinus, ui_event_DayMinus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DayPlus, ui_event_DayPlus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HourMinus, ui_event_HourMinus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HourPlus, ui_event_HourPlus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MinMinus, ui_event_MinMinus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MinPlus, ui_event_MinPlus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SecMinus, ui_event_SecMinus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SecPlus, ui_event_SecPlus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnSetTimeApply, ui_event_btnSetTimeApply, LV_EVENT_ALL, NULL);

}

void ui_SetTime_screen_destroy(void)
{
   if (ui_SetTime) lv_obj_del(ui_SetTime);

// NULL screen variables
ui_SetTime= NULL;
ui_SetTimeTitle= NULL;
ui_btnSetTimeBack= NULL;
ui_btnSetTimeBackLbl= NULL;
ui_LabelYear= NULL;
ui_YearMinus= NULL;
ui_YearMinusLbl= NULL;
ui_SpinboxYear= NULL;
ui_YearPlus= NULL;
ui_YearPlusLbl= NULL;
ui_LabelMonth= NULL;
ui_MonthMinus= NULL;
ui_MonthMinusLbl= NULL;
ui_SpinboxMonth= NULL;
ui_MonthPlus= NULL;
ui_MonthPlusLbl= NULL;
ui_LabelDay= NULL;
ui_DayMinus= NULL;
ui_DayMinusLbl= NULL;
ui_SpinboxDay= NULL;
ui_DayPlus= NULL;
ui_DayPlusLbl= NULL;
ui_LabelHour= NULL;
ui_HourMinus= NULL;
ui_HourMinusLbl= NULL;
ui_SpinboxHour= NULL;
ui_HourPlus= NULL;
ui_HourPlusLbl= NULL;
ui_LabelMin= NULL;
ui_MinMinus= NULL;
ui_MinMinusLbl= NULL;
ui_SpinboxMin= NULL;
ui_MinPlus= NULL;
ui_MinPlusLbl= NULL;
ui_LabelSec= NULL;
ui_SecMinus= NULL;
ui_SecMinusLbl= NULL;
ui_SpinboxSec= NULL;
ui_SecPlus= NULL;
ui_SecPlusLbl= NULL;
ui_btnSetTimeApply= NULL;
ui_btnSetTimeApplyLbl= NULL;

}
