// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Setting
extern void ui_Setting_screen_init(void);
extern void ui_Setting_screen_destroy(void);
extern lv_obj_t *ui_Setting;
extern lv_obj_t *ui_sleepDisplay;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label6;
extern void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Interval;
extern void ui_event_Dump( lv_event_t * e);
extern lv_obj_t *ui_Dump;
extern lv_obj_t *ui_Label15;
extern void ui_event_Back( lv_event_t * e);
extern lv_obj_t *ui_Back;
extern lv_obj_t *ui_Label8;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Spinbox1;
extern void ui_event_Button9( lv_event_t * e);
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label4;
extern void ui_event_Button10( lv_event_t * e);
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Spinbox2;
extern void ui_event_Button12( lv_event_t * e);
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Spinbox3;
extern void ui_event_Button13( lv_event_t * e);
extern lv_obj_t *ui_Button13;
extern lv_obj_t *ui_Label19;
extern void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Interval1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

