// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Monita_Controller

#ifndef _MONITA_CONTROLLER_UI_SETTIME_H
#define _MONITA_CONTROLLER_UI_SETTIME_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../ui.h"

// SCREEN: ui_SetTime
extern void ui_SetTime_screen_init(void);
extern void ui_SetTime_screen_destroy(void);
extern lv_obj_t *ui_SetTime;
extern lv_obj_t *ui_SpinboxYear;
extern lv_obj_t *ui_SpinboxMonth;
extern lv_obj_t *ui_SpinboxDay;
extern lv_obj_t *ui_SpinboxHour;
extern lv_obj_t *ui_SpinboxMin;
extern lv_obj_t *ui_SpinboxSec;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
