; 検証 Step7: スリープ＋起床時自動同期（子機）
; 親機は 04_ble_time_sync/parent を使用
[env:seeed_xiao_nrf52840]
platform  = https://github.com/Seeed-Studio/platform-seeedboards.git
board     = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags = -D USE_TINYUSB
lib_deps =
  adafruit/RTClib@^2.1.4
  adafruit/Adafruit BusIO@^1.16.0
