; PlatformIO Project Configuration File
; Multi-Channel Strain Measurement System ver 7
; Target: Arduino Mega 2560 + HX711 x20 + M5Stamp SIM7080G (SORACOM)

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
lib_deps =
    bogde/HX711@^0.7.5
    adafruit/Adafruit SHT4x Library@^1.0.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
