; iPEC サーバー通信検証 — Step1: HTTPS POST
; XIAO nRF52840 + SIM7080G (Flex v3.02 基板)

[env:seeed_xiao_nrf52840]
platform  = nordicnrf52
board     = seeed_xiao_nrf52840
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit TinyUSB Library@^3.4.4
